stages:
  - test

test_game_imports:
  tags:
    - edu
  image: python:3.10
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - python -c "import pygame; print('Pygame import successful')"
